# Generated by Django 5.1.3 on 2024-12-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('cpname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cpcode', models.PositiveSmallIntegerField()),
                ('cname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
